name: lint

on: [pull_request]

jobs:
  server:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install --requirement requirements.txt

      - name: Run black
        run: |
          black \
          --check \
          --config pyproject.toml \
          bootstrap.py

      - name: Run flake8
        run: |
          flake8 \
          --config setup.cfg \
          bootstrap.py
